let student = " you guys are doing great in learning JS ";
console.log(student.length);
console.log(student.toLowerCase());
console.log(student.toUpperCase());
console.log(student.includes("doing"));
console.log(student.charAt(5));
console.log(student.indexOf("u"));
console.log(student.lastIndexOf("u"));
console.log(student.slice(1,8));
console.log(student.replace('JS',"Java"));
console.log(student.split(' '));
console.log(student.startsWith(' '));
console.log(student.endsWith('S'));
console.log(student.trim());
console.log(student.trimStart());
console.log(student.trimEnd());
console.log(student.concat("and selenium with phython"));
console.log("Repeated 2 times:", student.repeat(3));
console.log(student.padStart(50,'*'));
console.log(student.padEnd(50,'&'));
console.log(`----------------------------------------------------------------------`);
console.log("Substring (0, 10):", student.substring(0, 12));
console.log("Substr (0, 5):", student.substr(0, 12));
console.log("CharCodeAt (0):", student.charCodeAt(3));